/**
 * Dashboard Page — Stats, Charts, Activity Feed, AI Suggestions
 *
 * Accessibility improvements:
 * - Stat cards use role="figure" + aria-label with values
 * - Chart container has role="img" + aria-label describing the data
 * - AI Insights button has aria-busy for loading state
 * - Activity feed uses role="feed" + time element for timestamps
 * - Live region announces AI suggestion load status
 * - Section headings use proper h2 hierarchy under the page h1
 */

import React, { useState, useEffect } from 'react';
import { CheckSquare, Clock, AlertTriangle, TrendingUp, Sparkles, Activity } from 'lucide-react';
import { Line } from 'react-chartjs-2';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Filler,
  Legend
} from 'chart.js';
import { taskApi, aiApi } from '../services/taskApi';
import { LoadingSpinner } from '../components/common/CommonComponents';
import { formatRelative } from '../utils/formatters';

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Filler, Legend);

export default function Dashboard() {
  const [stats, setStats] = useState(null);
  const [aiSuggestion, setAiSuggestion] = useState(null);
  const [loading, setLoading] = useState(true);
  const [aiLoading, setAiLoading] = useState(false);
  const [aiStatus, setAiStatus] = useState('');

  const teamId = localStorage.getItem('syncsphere-active-team');

  useEffect(() => {
    if (teamId) loadStats();
    else setLoading(false);
  }, [teamId]);

  const loadStats = async () => {
    try {
      const res = await taskApi.getStats(teamId);
      setStats(res.data);
    } catch (err) {
      console.error('Stats load error:', err);
    }
    setLoading(false);
  };

  const loadAiSuggestions = async () => {
    if (!teamId) return;
    setAiLoading(true);
    setAiStatus('Loading AI recommendations from Vertex AI...');
    try {
      const res = await aiApi.suggest(teamId);
      setAiSuggestion(res.data);
      setAiStatus('AI recommendations loaded successfully.');
    } catch (err) {
      console.error('AI suggestion error:', err);
      setAiStatus('Failed to load AI recommendations.');
    }
    setAiLoading(false);
  };

  const chartData = {
    labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    datasets: [{
      label: 'Tasks Completed',
      data: [3, 5, 4, 7, 6, 2, 4],
      fill: true,
      borderColor: '#6366f1',
      backgroundColor: 'rgba(99, 102, 241, 0.1)',
      borderWidth: 2,
      tension: 0.4,
      pointBackgroundColor: '#6366f1',
      pointBorderWidth: 0,
      pointRadius: 4,
      pointHoverRadius: 6
    }]
  };

  const chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
      tooltip: {
        backgroundColor: '#1a1a2e',
        borderColor: '#6366f1',
        borderWidth: 1
      }
    },
    scales: {
      x: { grid: { display: false }, ticks: { color: '#64748b' } },
      y: { grid: { color: 'rgba(148,163,184,0.08)' }, ticks: { color: '#64748b' }, beginAtZero: true }
    }
  };

  if (loading) return <LoadingSpinner text="Loading dashboard..." />;

  const statCards = [
    { icon: CheckSquare, label: 'Total Tasks', value: stats?.total || 0, color: '#6366f1' },
    { icon: TrendingUp, label: 'Completed', value: stats?.done_count || 0, color: '#10b981' },
    { icon: Clock, label: 'In Progress', value: stats?.in_progress_count || 0, color: '#3b82f6' },
    { icon: AlertTriangle, label: 'Overdue', value: stats?.overdue_count || 0, color: '#ef4444' },
  ];

  const recentActivity = [
    { text: 'Task "Design UI" completed', time: new Date(Date.now() - 0 * 3600000) },
    { text: 'New task "API Integration" created', time: new Date(Date.now() - 1 * 3600000) },
    { text: 'Team standup summary generated by AI', time: new Date(Date.now() - 2 * 3600000) },
  ];

  return (
    <div className="dashboard animate-fade-in">
      {/* ARIA live region: announces AI loading status to screen readers */}
      <div aria-live="polite" aria-atomic="true" className="visually-hidden">
        {aiStatus}
      </div>

      <div className="d-flex align-items-center justify-content-between mb-4">
        <div>
          <h1 className="h3 fw-bold mb-1">Dashboard</h1>
          <p style={{ color: 'var(--text-secondary)' }}>Welcome back! Here&apos;s your team overview.</p>
        </div>
        <button
          className="btn btn-primary d-flex align-items-center gap-2"
          onClick={loadAiSuggestions}
          disabled={aiLoading}
          aria-busy={aiLoading}
          aria-label={aiLoading ? 'Loading AI insights from Vertex AI...' : 'Load AI insights from Vertex AI'}
        >
          <Sparkles size={18} aria-hidden="true" />
          {aiLoading ? 'Analyzing...' : 'AI Insights'}
        </button>
      </div>

      {/* Stats Cards */}
      <section aria-label="Team task statistics">
        <div className="row g-3 mb-4 stagger-children">
          {statCards.map((card, i) => (
            <div key={i} className="col-6 col-lg-3">
              <div
                className="stat-card"
                role="figure"
                aria-label={`${card.label}: ${card.value}`}
              >
                <div className="d-flex align-items-center gap-2 mb-2">
                  <card.icon size={20} style={{ color: card.color }} aria-hidden="true" />
                  <span className="stat-label">{card.label}</span>
                </div>
                <div className="stat-value" aria-hidden="true">{card.value}</div>
              </div>
            </div>
          ))}
        </div>
      </section>

      <div className="row g-3">
        {/* Productivity Chart */}
        <div className="col-lg-8">
          <section
            className="glass-card p-4"
            style={{ height: 350 }}
            aria-label="Weekly productivity chart"
          >
            <h2 className="fw-bold mb-3" style={{ fontSize: '1rem' }}>
              <TrendingUp size={18} className="me-2" style={{ color: 'var(--primary)' }} aria-hidden="true" />
              Weekly Productivity
            </h2>
            {/* Chart wrapped in figure with accessible description */}
            <figure
              style={{ height: 270, margin: 0 }}
              role="img"
              aria-label={`Line chart showing tasks completed each day this week: Mon: 3, Tue: 5, Wed: 4, Thu: 7, Fri: 6, Sat: 2, Sun: 4`}
            >
              <Line data={chartData} options={chartOptions} />
            </figure>
          </section>
        </div>

        {/* AI Suggestions */}
        <div className="col-lg-4">
          <section
            className="glass-card p-4"
            style={{ height: 350, overflowY: 'auto' }}
            aria-label="AI recommendations from Vertex AI"
            aria-live="polite"
          >
            <h2 className="fw-bold mb-3" style={{ fontSize: '1rem' }}>
              <Sparkles size={18} className="me-2" style={{ color: 'var(--accent)' }} aria-hidden="true" />
              AI Recommendations
            </h2>
            {aiSuggestion ? (
              <div
                style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', whiteSpace: 'pre-wrap' }}
                aria-label="AI recommendations content"
              >
                {aiSuggestion.suggestions}
              </div>
            ) : (
              <div className="text-center py-4" aria-label="No AI recommendations yet">
                <Sparkles size={32} style={{ color: 'var(--text-muted)' }} aria-hidden="true" />
                <p className="mt-2 small" style={{ color: 'var(--text-muted)' }}>
                  Click &quot;AI Insights&quot; to get smart recommendations powered by Vertex AI Gemini Pro
                </p>
              </div>
            )}
          </section>
        </div>
      </div>

      {/* Activity Feed */}
      <section
        className="glass-card p-4 mt-3"
        aria-label="Recent team activity"
      >
        <h2 className="fw-bold mb-3" style={{ fontSize: '1rem' }}>
          <Activity size={18} className="me-2" style={{ color: 'var(--info)' }} aria-hidden="true" />
          Recent Activity
        </h2>
        {/* role="feed" is the correct ARIA role for activity streams */}
        <div className="d-flex flex-column gap-2" role="feed" aria-label="Recent activity items">
          {recentActivity.map((item, i) => (
            <article
              key={i}
              className="d-flex align-items-center gap-3 p-2 rounded"
              style={{ background: 'var(--bg-hover)' }}
              aria-label={item.text}
            >
              <div
                style={{ width: 8, height: 8, borderRadius: '50%', background: 'var(--primary)', flexShrink: 0 }}
                aria-hidden="true"
              />
              <span className="small">{item.text}</span>
              <time
                className="ms-auto small"
                style={{ color: 'var(--text-muted)' }}
                dateTime={item.time.toISOString()}
                aria-label={`${formatRelative(item.time)} ago`}
              >
                {formatRelative(item.time)}
              </time>
            </article>
          ))}
        </div>
      </section>
    </div>
  );
}
